if __name__ == '__main__':
    PNOUN1 = input("A plural noun: ")
    FNAME = input("A person's first name: ")
    NOUN1 = input('A noun: ')
    LNAME = input('A person last name: ')
    PNOUN2 = input("A second plural noun: ")
    PLACE1 = input('A place')
    PNOUN3 = input("A third plural noun: ")
    PLACE2 = input('Another place')
    PNOUN4 = input("A fourth plural noun: ")
    NOUN2 = input('A second noun: ')
    ADJECTIVE1 = input('An adjective: ')
    ADJECTIVE2 = input('A second adjective: ')
    VERB = input('A verb: ')
    ADJECTIVE3 = input('A third adjective: ')

    print('Hello there, sports {}'.format(PNOUN1))
    print('This is {}, talking to the press {}'.format(FNAME, PNOUN2))
    print('in {} stadium where 57,000 people cheering {}'.format(LNAME, PNOUN2))
    print('Having gathered to watch the {} {}'.format(PLACE1, PNOUN3))
    print('take on the {} {} '.format(PLACE2, PNOUN4))
    print('Even though the {} is shining, its an {}'.format(NOUN2, ADJECTIVE1))
    print('cold day with the temperature in the {} 20s'.format(ADJECTIVE2))
    print("We'll be back for the opening {} off after a few word from our {} sponsor".format(VERB, ADJECTIVE3))